### ISSUE TITLE
Multiple containers

### ISSUE THREAD

**Issue by mogmog** [felixpalmer/procedural-gl-js#14]
At the moment it seems to be the case that there can only be 1 Procedural container in the DOM. Despite the performance hit having multiple, is this something that is on the road map?

**Comment by felixpalmer** [comment]
This is not currently on the roadmap, in part because it would inevitably hurt performance.

Could you add some more detail about the use case you're trying to solve? Two approaches you could take now are:

- Use iframes to get two instances on one page
- Move the DOM element with the Procedural map in it to different locations depending on where you need it, and re-configure the map each time to the new location

**Comment by mogmog** [comment]
The user case is having embedded vignettes of various mountains on a page. The engine doesn't need to be running for animation purposes for this, only one is interacted with at a time. 

I've been experimenting with option 2, it requires a bit of extra work as I'm using React which is a little less forgiving when it comes to Dom manipulation like this.

**Comment by mogmog** [comment]
For anyone else in this situation, I have had some preliminary success with the following library:

https://github.com/httptoolkit/react-reverse-portal#readme
